CREATE TABLE IF NOT EXISTS interview_personas (
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    title VARCHAR(50) NOT NULL,
    style VARCHAR(200) NOT NULL,
    avatar VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'preset',
    user_id BIGINT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
