// 国内大厂校招官网目录：纯本地静态数据，点击在新标签页打开官网，本产品不做任何投递代理。
// 官网地址以各公司官方发布为准。
export interface CareerSite {
  company: string
  name: string
  url: string
}

export const CAREER_SITES: CareerSite[] = [
  { company: '腾讯', name: '腾讯校招', url: 'https://join.qq.com/' },
  { company: '字节跳动', name: '字节跳动校招', url: 'https://jobs.bytedance.com/campus' },
  { company: '阿里巴巴', name: '阿里校招', url: 'https://talent.alibaba.com/campus' },
  { company: '美团', name: '美团校招', url: 'https://campus.meituan.com/' },
  { company: '百度', name: '百度校招', url: 'https://talent.baidu.com/campus' },
  { company: '网易', name: '网易校招', url: 'https://camp.163.com/' },
  { company: '华为', name: '华为校招', url: 'https://career.huawei.com/' },
  { company: '小米', name: '小米校招', url: 'https://hr.xiaomi.com/campus' },
  { company: '京东', name: '京东校招', url: 'https://campus.jd.com/' },
  { company: '拼多多', name: '拼多多招聘', url: 'https://careers.pinduoduo.com/' },
  { company: '快手', name: '快手招聘', url: 'https://zhaopin.kuaishou.cn/' },
  { company: '哔哩哔哩', name: 'B站招聘', url: 'https://jobs.bilibili.com/' },
  { company: '滴滴', name: '滴滴校招', url: 'https://campus.didiglobal.com/' },
  { company: '大疆', name: '大疆校招', url: 'https://we.dji.com/zh-CN/campus' },
  { company: 'OPPO', name: 'OPPO 招聘', url: 'https://careers.oppo.com/' },
  { company: 'vivo', name: 'vivo 校招', url: 'https://campus.vivo.com/' },
  { company: '小红书', name: '小红书招聘', url: 'https://job.xiaohongshu.com/' },
  { company: '米哈游', name: '米哈游招聘', url: 'https://join.mihoyo.com/' },
  { company: '荣耀', name: '荣耀招聘', url: 'https://career.honor.com/' },
  { company: '比亚迪', name: '比亚迪招聘', url: 'https://bydglobal.51job.com/' },
  { company: '科大讯飞', name: '科大讯飞招聘', url: 'https://career.iflytek.com/' },
  { company: '海康威视', name: '海康威视校招', url: 'https://campus.hikvision.com/' },
  { company: '宁德时代', name: '宁德时代校招', url: 'https://camp.catl.com/' },
  { company: '蔚来', name: '蔚来招聘', url: 'https://nio.com/careers' },
  { company: '小鹏汽车', name: '小鹏招聘', url: 'https://job.xiaopeng.com/' },
  { company: '商汤科技', name: '商汤招聘', url: 'https://careers.sensetime.com/' },
  { company: 'TCL', name: 'TCL 招聘', url: 'https://jobs.tcl.com/' },
  { company: '浪潮', name: '浪潮招聘', url: 'https://campus.inspur.com/' },
  { company: '联想', name: '联想校招', url: 'https://campus.lenovo.com/' },
  { company: '中兴', name: '中兴招聘', url: 'https://job.zte.com.cn/' },
  { company: '大华', name: '大华招聘', url: 'https://campus.dahuatech.com/' },
  { company: '360', name: '360 招聘', url: 'https://campus.360.cn/' },
  { company: '携程', name: '携程招聘', url: 'https://career.ctrip.com/' },
  { company: '唯品会', name: '唯品会校招', url: 'https://campus.vip.com/' },
  { company: '知乎', name: '知乎招聘', url: 'https://www.zhihu.com/careers' },
  { company: '虎牙', name: '虎牙招聘', url: 'https://hr.huya.com/' },
  { company: '斗鱼', name: '斗鱼招聘', url: 'https://join.douyu.com/' },
  { company: '得物', name: '得物招聘', url: 'https://careers.dewu.com/' },
  { company: '顺丰速运', name: '顺丰校招', url: 'https://campus.sf-express.com/' },
  { company: '平安', name: '平安集团校招', url: 'https://campus.pingan.com/' },
  { company: '招商银行', name: '招商银行校招', url: 'https://career.cmbchina.com/' },
  { company: '交通银行', name: '交通银行招聘', url: 'https://job.bankcomm.com/' },
  { company: '建设银行', name: '建设银行招聘', url: 'https://job.ccb.com/' },
  { company: '工商银行', name: '工商银行招聘', url: 'https://job.icbc.com.cn/' },
  { company: '中国银行', name: '中国银行招聘', url: 'https://campus.bank-of-china.com/' },
  { company: '农业银行', name: '农业银行招聘', url: 'https://job.abchina.com/' },
  { company: '中金公司', name: '中金招聘', url: 'https://www.cicc.com/careers/' },
  { company: '网易有道', name: '网易有道招聘', url: 'https://job.youdao.com/' },
  { company: '携程旅行', name: 'Trip.com 招聘', url: 'https://trip.jobs/' },
  { company: '贝壳', name: '贝壳招聘', url: 'https://campus.ke.com/' },
  { company: '莉莉丝游戏', name: '莉莉丝招聘', url: 'https://campus.lilith.com/' },
  { company: '完美世界', name: '完美世界校招', url: 'https://campus.wanmei.com/' },
  { company: '传音控股', name: '传音招聘', url: 'https://campus.transsion.com/' },
  { company: '歌尔股份', name: '歌尔校招', url: 'https://campus.goertek.com/' },
  { company: '海尔', name: '海尔招聘', url: 'https://campus.haier.net/' },
  { company: '美的集团', name: '美的校招', url: 'https://campus.midea.com/' },
  { company: '格力电器', name: '格力招聘', url: 'https://zhaopin.gree.com/' },
  { company: '金山办公', name: '金山办公校招', url: 'https://campus.wps.cn/' },
  { company: '用友', name: '用友招聘', url: 'https://campus.yonyou.com/' },
  { company: '中国移动', name: '中国移动招聘', url: 'https://job.10086.cn/' },
  { company: '中国电信', name: '中国电信校招', url: 'https://campus.chinatelecom.cn/' },
  { company: '中国联通', name: '中国联通招聘', url: 'https://career.chinaunicom.cn/' },
  { company: '中信证券', name: '中信证券招聘', url: 'https://careers.cs.ecitic.com/' },
  { company: '华泰证券', name: '华泰证券招聘', url: 'https://job.htsc.com.cn/' },
  { company: '中国人寿', name: '中国人寿招聘', url: 'https://campus.chinalife.com.cn/' },
  { company: '新东方', name: '新东方校招', url: 'https://campus.xdf.cn/' },
  { company: '好未来', name: '好未来招聘', url: 'https://job.tal.com/' },
  { company: '吉利汽车', name: '吉利招聘', url: 'https://recruit.geely.com/' },
  { company: '长城汽车', name: '长城汽车校招', url: 'https://campus.gwm.com.cn/' },
  { company: '上汽集团', name: '上汽招聘', url: 'https://campus.saicmotor.com/' },
  { company: '中国中车', name: '中国中车招聘', url: 'https://ccd.crrcgc.cc/' },
  { company: '国网', name: '国家电网招聘', url: 'https://zhaopin.sgcc.com.cn/' },
  { company: '中石油', name: '中石油招聘', url: 'https://zhaopin.cnpc.com.cn/' },
  { company: '中石化', name: '中石化招聘', url: 'https://job.sinopec.com/' },
  { company: '中国中免', name: '中免招聘', url: 'https://campus.cdfg.com.cn/' },
  { company: '海底捞', name: '海底捞招聘', url: 'https://xyz.haidilao.com/' },
  { company: '蜜雪冰城', name: '蜜雪冰城招聘', url: 'https://mxbsp.hr-mp.com/' },
  { company: '瑞幸咖啡', name: '瑞幸招聘', url: 'https://app.mokahr.com/careers/luckincoffee' },
  { company: '泡泡玛特', name: '泡泡玛特招聘', url: 'https://campus.popmart.com/' },
  { company: '安踏', name: '安踏招聘', url: 'https://career.anta.com/' },
  { company: '李宁', name: '李宁招聘', url: 'https://zhaopin.li-ning.com/' },
  { company: '波司登', name: '波司登招聘', url: 'https://campus.bosideng.com/' },
  { company: '同花顺', name: '同花顺招聘', url: 'https://campus.myhexin.com/' },
  { company: '东方财富', name: '东方财富招聘', url: 'https://zhaopin.eastmoney.com/' },
  { company: '微众银行', name: '微众银行校招', url: 'https://campus.webank.com/' },
  { company: '网商银行', name: '网商银行招聘', url: 'https://campus.mybank.cn/' },
  { company: '转转', name: '转转招聘', url: 'https://hr.zhuanzhuan.com/' },
  { company: '携程商旅', name: '携程商旅招聘', url: 'https://career.ctrip.com/' },
  { company: '途虎养车', name: '途虎招聘', url: 'https://campus.tuhu.cn/' },
  { company: '贝壳如视', name: '贝壳招聘', url: 'https://campus.ke.com/' },
  { company: '猎豹移动', name: '猎豹招聘', url: 'https://www.cmcm.com/careers/' },
  { company: '迅雷', name: '迅雷招聘', url: 'https://campus.xunlei.com/' },
  { company: '暴风', name: '暴风招聘', url: 'https://www.baofeng.com/' },
  { company: '搜狐', name: '搜狐招聘', url: 'https://careers.sohu.com/' },
  { company: '新浪', name: '新浪招聘', url: 'https://careers.sina.com.cn/' },
  { company: '字节青训', name: '字节跳动青训营', url: 'https://education.bytedance.com/' },
  { company: '快手电商', name: '快手电商招聘', url: 'https://zhaopin.kuaishou.cn/' },
  { company: '百度智能云', name: '百度智能云招聘', url: 'https://cloud.baidu.com/careers/' },
  { company: '阿里钉钉', name: '钉钉招聘', url: 'https://job.dingtalk.com/' },
  { company: '腾讯云', name: '腾讯云招聘', url: 'https://careers.tencent.com/cloud.html' },
]