CREATE TABLE job_stage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    stage VARCHAR(20) NOT NULL,
    occurred_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_stage_events_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_job_stage_events_project FOREIGN KEY (project_id) REFERENCES job_projects (id) ON DELETE CASCADE,
    CONSTRAINT chk_job_stage_events_stage CHECK (stage IN ('applied', 'exam', 'interview', 'hr', 'offer', 'closed'))
);
CREATE INDEX idx_job_stage_events_project ON job_stage_events(project_id, occurred_at);
