-- ResumeGo desktop/local workspace schema.
-- This is a clean baseline for new H2 file databases. Published MySQL migrations
-- stay unchanged and continue to serve existing server installations.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_invocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NULL,
    feature_type VARCHAR(50) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    status VARCHAR(32) NOT NULL,
    latency_ms INT NULL,
    schema_valid BOOLEAN NULL,
    input_tokens INT NULL,
    output_tokens INT NULL,
    error_category VARCHAR(50) NULL,
    prompt_summary VARCHAR(200) NULL,
    response_summary VARCHAR(200) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_invocations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX idx_ai_invocations_user_id ON ai_invocations(user_id);
CREATE INDEX idx_ai_invocations_feature_created_at ON ai_invocations(feature_type, created_at);

CREATE TABLE capability_evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    evidence_type VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    situation TEXT NULL,
    action_text TEXT NOT NULL,
    result_text TEXT NULL,
    skill_tags TEXT NOT NULL,
    source_note VARCHAR(500) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3) NULL,
    CONSTRAINT fk_capability_evidences_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_capability_evidences_type CHECK (evidence_type IN ('project', 'internship', 'competition', 'skill', 'other'))
);
CREATE INDEX idx_capability_evidences_user_id ON capability_evidences(user_id);
CREATE INDEX idx_capability_evidences_type ON capability_evidences(evidence_type);

CREATE TABLE job_descriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_title VARCHAR(200) NOT NULL,
    company_name VARCHAR(200) NULL,
    raw_text CLOB NOT NULL,
    parsed_json CLOB NULL,
    parse_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    prompt_version VARCHAR(50) NULL,
    parse_ai_invocation_id BIGINT NULL,
    source_meta_json CLOB NULL,
    job_type VARCHAR(50) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_descriptions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_job_descriptions_parse_ai FOREIGN KEY (parse_ai_invocation_id) REFERENCES ai_invocations (id) ON DELETE SET NULL,
    CONSTRAINT chk_job_descriptions_parse_status CHECK (parse_status IN ('pending', 'succeeded', 'failed'))
);
CREATE INDEX idx_job_descriptions_user_id ON job_descriptions(user_id);
CREATE INDEX idx_job_descriptions_parse_ai ON job_descriptions(parse_ai_invocation_id);

CREATE TABLE resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    current_version_id BIGINT NULL,
    target_job_description_id BIGINT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(3) NULL,
    CONSTRAINT fk_resumes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_resumes_target_job FOREIGN KEY (target_job_description_id) REFERENCES job_descriptions (id) ON DELETE SET NULL
);
CREATE INDEX idx_resumes_user_id ON resumes(user_id);
CREATE INDEX idx_resumes_current_version_id ON resumes(current_version_id);
CREATE INDEX idx_resumes_target_job_id ON resumes(target_job_description_id);

CREATE TABLE resume_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_id BIGINT NOT NULL,
    parent_version_id BIGINT NULL,
    version_no INT NOT NULL,
    content_json CLOB NOT NULL,
    change_summary VARCHAR(500) NULL,
    created_by_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resume_versions_resume_no UNIQUE (resume_id, version_no),
    CONSTRAINT fk_resume_versions_resume FOREIGN KEY (resume_id) REFERENCES resumes (id),
    CONSTRAINT fk_resume_versions_parent FOREIGN KEY (parent_version_id) REFERENCES resume_versions (id),
    CONSTRAINT chk_resume_versions_created_by CHECK (created_by_type IN ('user', 'ai_suggestion', 'import'))
);
CREATE INDEX idx_resume_versions_resume_id ON resume_versions(resume_id);
CREATE INDEX idx_resume_versions_parent_id ON resume_versions(parent_version_id);
ALTER TABLE resumes ADD CONSTRAINT fk_resumes_current_version FOREIGN KEY (current_version_id) REFERENCES resume_versions (id) ON DELETE SET NULL;

CREATE TABLE resume_evidence_refs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_version_id BIGINT NOT NULL,
    evidence_id BIGINT NOT NULL,
    section_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resume_evidence_ref UNIQUE (resume_version_id, evidence_id, section_key),
    CONSTRAINT fk_resume_evidence_refs_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id),
    CONSTRAINT fk_resume_evidence_refs_evidence FOREIGN KEY (evidence_id) REFERENCES capability_evidences (id)
);
CREATE INDEX idx_resume_evidence_refs_evidence ON resume_evidence_refs(evidence_id);

CREATE TABLE resume_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_version_id BIGINT NOT NULL,
    rule_version VARCHAR(50) NOT NULL,
    total_score DECIMAL(5,2) NOT NULL,
    dimension_scores CLOB NOT NULL,
    deductions CLOB NOT NULL,
    input_fingerprint CHAR(64) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_resume_assessments_input UNIQUE (resume_version_id, rule_version, input_fingerprint),
    CONSTRAINT fk_resume_assessments_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id),
    CONSTRAINT chk_resume_assessments_score CHECK (total_score >= 0 AND total_score <= 100)
);
CREATE INDEX idx_resume_assessments_version ON resume_assessments(resume_version_id);

CREATE TABLE job_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resume_version_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    algorithm_version VARCHAR(50) NOT NULL,
    match_score DECIMAL(5,2) NOT NULL,
    details_json CLOB NOT NULL,
    input_fingerprint CHAR(64) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_job_matches_input UNIQUE (resume_version_id, job_description_id, algorithm_version, input_fingerprint),
    CONSTRAINT fk_job_matches_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id),
    CONSTRAINT fk_job_matches_job FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id),
    CONSTRAINT chk_job_matches_score CHECK (match_score >= 0 AND match_score <= 100)
);
CREATE INDEX idx_job_matches_version ON job_matches(resume_version_id);
CREATE INDEX idx_job_matches_job ON job_matches(job_description_id);

CREATE TABLE optimization_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_match_id BIGINT NOT NULL,
    resume_version_id BIGINT NOT NULL,
    evidence_id BIGINT NULL,
    section_key VARCHAR(100) NOT NULL,
    original_text CLOB NOT NULL,
    suggested_text CLOB NULL,
    reason_text CLOB NOT NULL,
    target_requirement CLOB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    risk_level VARCHAR(32) NULL,
    prompt_version VARCHAR(50) NOT NULL,
    generation_ai_invocation_id BIGINT NOT NULL,
    accepted_version_id BIGINT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMP(3) NULL,
    CONSTRAINT fk_optimization_job_match FOREIGN KEY (job_match_id) REFERENCES job_matches (id),
    CONSTRAINT fk_optimization_resume_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id),
    CONSTRAINT fk_optimization_evidence FOREIGN KEY (evidence_id) REFERENCES capability_evidences (id) ON DELETE SET NULL,
    CONSTRAINT fk_optimization_ai FOREIGN KEY (generation_ai_invocation_id) REFERENCES ai_invocations (id),
    CONSTRAINT fk_optimization_accepted_version FOREIGN KEY (accepted_version_id) REFERENCES resume_versions (id) ON DELETE SET NULL,
    CONSTRAINT chk_optimization_status CHECK (status IN ('pending', 'accepted', 'rejected', 'evidence_required', 'high_risk')),
    CONSTRAINT chk_optimization_evidence_required CHECK ((status = 'evidence_required' AND suggested_text IS NULL) OR status <> 'evidence_required')
);
CREATE INDEX idx_optimization_job_match ON optimization_suggestions(job_match_id);
CREATE INDEX idx_optimization_resume_version ON optimization_suggestions(resume_version_id);

CREATE TABLE interview_personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    title VARCHAR(50) NOT NULL,
    style VARCHAR(200) NOT NULL,
    avatar VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'preset',
    user_id BIGINT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_interview_personas_type ON interview_personas(type);
CREATE INDEX idx_interview_personas_user_id ON interview_personas(user_id);

CREATE TABLE interview_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resume_version_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL DEFAULT '多轮模拟面试',
    question_count INT NOT NULL DEFAULT 5,
    persona_plan_json CLOB NOT NULL,
    focus_tags_json CLOB NULL,
    supplement_text CLOB NULL,
    summary_json CLOB NULL,
    summary_generated_at TIMESTAMP(3) NULL,
    deleted_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_plans_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_interview_plans_resume_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id),
    CONSTRAINT fk_interview_plans_job FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id)
);
CREATE INDEX idx_interview_plans_user_created ON interview_plans(user_id, created_at);

CREATE TABLE interview_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resume_version_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'READY',
    current_question_index INT NOT NULL DEFAULT 0,
    total_questions INT NOT NULL DEFAULT 3,
    started_at TIMESTAMP(3) NULL,
    completed_at TIMESTAMP(3) NULL,
    summary_json CLOB NULL,
    persona_id BIGINT NULL,
    persona_name VARCHAR(20) NULL,
    persona_title VARCHAR(50) NULL,
    plan_id BIGINT NULL,
    round_order INT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_interview_sessions_plan_round UNIQUE (plan_id, round_order),
    CONSTRAINT fk_interview_sessions_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_interview_sessions_resume_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id),
    CONSTRAINT fk_interview_sessions_job FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id),
    CONSTRAINT fk_interview_sessions_plan FOREIGN KEY (plan_id) REFERENCES interview_plans (id),
    CONSTRAINT chk_interview_sessions_status CHECK (status IN ('READY', 'ASKING', 'WAITING_ANSWER', 'EVALUATING', 'SUMMARIZING', 'COMPLETED', 'FAILED', 'CANCELLED'))
);
CREATE INDEX idx_interview_sessions_user_id ON interview_sessions(user_id);
CREATE INDEX idx_interview_sessions_plan_id ON interview_sessions(plan_id);

CREATE TABLE interview_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_index INT NOT NULL,
    question_text CLOB NOT NULL,
    question_type VARCHAR(50) NULL,
    target_skill VARCHAR(100) NULL,
    source VARCHAR(50) NOT NULL DEFAULT 'ai_generated',
    generation_ai_invocation_id BIGINT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_interview_questions_session_index UNIQUE (session_id, question_index),
    CONSTRAINT fk_interview_questions_session FOREIGN KEY (session_id) REFERENCES interview_sessions (id),
    CONSTRAINT fk_interview_questions_ai FOREIGN KEY (generation_ai_invocation_id) REFERENCES ai_invocations (id) ON DELETE SET NULL,
    CONSTRAINT chk_interview_questions_type CHECK (question_type IN ('behavioral', 'technical', 'situational', 'background', 'other')),
    CONSTRAINT chk_interview_questions_source CHECK (source IN ('ai_generated', 'system_defined', 'manual'))
);

CREATE TABLE interview_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL UNIQUE,
    answer_text CLOB NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_answers_session FOREIGN KEY (session_id) REFERENCES interview_sessions (id),
    CONSTRAINT fk_interview_answers_question FOREIGN KEY (question_id) REFERENCES interview_questions (id)
);

CREATE TABLE interview_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    answer_id BIGINT NOT NULL UNIQUE,
    score_json CLOB NULL,
    strengths_json CLOB NULL,
    weaknesses_json CLOB NULL,
    suggestions_json CLOB NULL,
    reference_answer_json CLOB NULL,
    evaluation_ai_invocation_id BIGINT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_evaluations_session FOREIGN KEY (session_id) REFERENCES interview_sessions (id),
    CONSTRAINT fk_interview_evaluations_question FOREIGN KEY (question_id) REFERENCES interview_questions (id),
    CONSTRAINT fk_interview_evaluations_answer FOREIGN KEY (answer_id) REFERENCES interview_answers (id),
    CONSTRAINT fk_interview_evaluations_ai FOREIGN KEY (evaluation_ai_invocation_id) REFERENCES ai_invocations (id) ON DELETE SET NULL
);

CREATE TABLE interview_growth_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    resume_id BIGINT NOT NULL,
    resume_version_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    interview_plan_id BIGINT NOT NULL UNIQUE,
    clarity_score DECIMAL(4,1) NOT NULL,
    relevance_score DECIMAL(4,1) NOT NULL,
    depth_score DECIMAL(4,1) NOT NULL,
    accuracy_score DECIMAL(4,1) NOT NULL,
    overall_score DECIMAL(4,1) NOT NULL,
    weak_points_json CLOB NULL,
    summary_text VARCHAR(500) NULL,
    completed_at TIMESTAMP(3) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_growth_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_interview_growth_resume FOREIGN KEY (resume_id) REFERENCES resumes (id),
    CONSTRAINT fk_interview_growth_resume_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id),
    CONSTRAINT fk_interview_growth_job FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id),
    CONSTRAINT fk_interview_growth_plan FOREIGN KEY (interview_plan_id) REFERENCES interview_plans (id)
);

CREATE TABLE company_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(120) NOT NULL,
    normalized_name VARCHAR(120) NOT NULL UNIQUE,
    source_type VARCHAR(40) NOT NULL DEFAULT 'experience_based',
    source_note VARCHAR(500) NULL,
    preference_tags CLOB NOT NULL,
    writing_style VARCHAR(500) NULL,
    interview_focus CLOB NULL,
    resume_advice_rules CLOB NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_company_profiles_source_type CHECK (source_type IN ('official', 'dataset', 'experience_based', 'manual'))
);

CREATE TABLE job_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    job_description_id BIGINT NULL,
    resume_version_id BIGINT NULL,
    archived_at TIMESTAMP(3) NULL,
    deleted_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_projects_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_job_projects_job FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id) ON DELETE SET NULL,
    CONSTRAINT fk_job_projects_resume_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE SET NULL,
    CONSTRAINT chk_job_projects_status CHECK (status IN ('active', 'archived'))
);
CREATE INDEX idx_job_projects_user_status ON job_projects(user_id, status, deleted_at);

-- The current single-user workspace services use id=1. This internal identity is
-- intentionally generic and does not prefill any resume, evidence, or job data.
INSERT INTO users (id, display_name) VALUES (1, 'Local User');
