-- 三模式契约：与 MySQL V40 等价的 H2 迁移。
-- 旧计划统一回填 ROLE_BASED 并按现有外键生成兼容快照：不复制简历/JD 正文，不伪造 Pipeline ID。

ALTER TABLE interview_plans ADD COLUMN mode VARCHAR(32) NOT NULL DEFAULT 'ROLE_BASED';
ALTER TABLE interview_plans ADD COLUMN context_contract_version VARCHAR(16) NOT NULL DEFAULT '1';
ALTER TABLE interview_plans ADD COLUMN start_context_snapshot_json CLOB NULL;

ALTER TABLE interview_plans ADD CONSTRAINT chk_interview_plans_mode
    CHECK (mode IN ('ROLE_BASED', 'KNOWLEDGE_TRAINING', 'EXPERIENCE_SIMULATION'));

UPDATE interview_plans
SET start_context_snapshot_json = CONCAT(
    '{"mode":"ROLE_BASED","contextContractVersion":"1","resumeVersionId":', resume_version_id,
    ',"jobDescriptionId":', job_description_id, '}')
WHERE start_context_snapshot_json IS NULL;

ALTER TABLE interview_plans ALTER COLUMN resume_version_id SET NULL;
ALTER TABLE interview_plans ALTER COLUMN job_description_id SET NULL;

CREATE TABLE interview_question_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_note VARCHAR(500) NULL,
    archived_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_interview_question_sets_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_interview_question_sets_source
        CHECK (source_type IN ('USER_MANUAL', 'IMPORTED_EXPERIENCE', 'GENERATED_PRACTICE'))
);
CREATE INDEX idx_interview_question_sets_user ON interview_question_sets(user_id, id);

CREATE TABLE interview_question_set_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL,
    position_index INT NOT NULL,
    question_text VARCHAR(1000) NOT NULL,
    CONSTRAINT uk_interview_question_set_items UNIQUE (set_id, position_index),
    CONSTRAINT fk_interview_question_set_items_set
        FOREIGN KEY (set_id) REFERENCES interview_question_sets (id)
        ON DELETE CASCADE
);
