CREATE TABLE schedule_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    start_time TIMESTAMP(3) NOT NULL,
    end_time TIMESTAMP(3) NULL,
    notes VARCHAR(1000) NULL,
    job_description_id BIGINT NULL,
    deleted_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_schedule_events_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_schedule_events_job_description FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id) ON DELETE SET NULL,
    CONSTRAINT chk_schedule_events_type CHECK (event_type IN ('interview', 'exam', 'followup', 'other'))
);
CREATE INDEX idx_schedule_events_user_time ON schedule_events(user_id, start_time, deleted_at);
