CREATE TABLE career_pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_project_id BIGINT NULL,
    name VARCHAR(120) NOT NULL,
    company_name VARCHAR(120) NOT NULL,
    role_title VARCHAR(160) NOT NULL,
    job_description_id BIGINT NULL,
    resume_version_id BIGINT NULL,
    lifecycle VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    outcome VARCHAR(20) NULL,
    current_stage_id BIGINT NULL,
    archived_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_career_pipelines_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_career_pipelines_source_project FOREIGN KEY (source_project_id) REFERENCES job_projects (id) ON DELETE SET NULL,
    CONSTRAINT fk_career_pipelines_job FOREIGN KEY (job_description_id) REFERENCES job_descriptions (id) ON DELETE SET NULL,
    CONSTRAINT fk_career_pipelines_resume_version FOREIGN KEY (resume_version_id) REFERENCES resume_versions (id) ON DELETE SET NULL,
    CONSTRAINT uk_career_pipelines_source_project UNIQUE (user_id, source_project_id),
    CONSTRAINT chk_career_pipelines_lifecycle CHECK (lifecycle IN ('ACTIVE', 'PAUSED', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT chk_career_pipelines_outcome CHECK (outcome IS NULL OR outcome IN ('OFFER', 'REJECTED', 'WITHDRAWN', 'OTHER')),
    CONSTRAINT chk_career_pipelines_closed_outcome CHECK ((lifecycle = 'CLOSED' AND outcome IS NOT NULL) OR (lifecycle <> 'CLOSED' AND outcome IS NULL))
);
CREATE INDEX idx_career_pipelines_user_lifecycle ON career_pipelines(user_id, lifecycle, updated_at);

CREATE TABLE pipeline_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    position_index INT NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pipeline_stages_pipeline FOREIGN KEY (pipeline_id) REFERENCES career_pipelines (id) ON DELETE CASCADE,
    CONSTRAINT uk_pipeline_stages_position UNIQUE (pipeline_id, position_index),
    CONSTRAINT chk_pipeline_stages_position CHECK (position_index >= 0),
    CONSTRAINT chk_pipeline_stages_state CHECK (state IN ('PENDING', 'CURRENT', 'COMPLETED', 'SKIPPED'))
);
CREATE INDEX idx_pipeline_stages_pipeline ON pipeline_stages(pipeline_id, position_index);

ALTER TABLE career_pipelines ADD CONSTRAINT fk_career_pipelines_current_stage
    FOREIGN KEY (current_stage_id) REFERENCES pipeline_stages (id) ON DELETE SET NULL;

CREATE TABLE pipeline_stage_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL,
    from_stage_id BIGINT NULL,
    to_stage_id BIGINT NOT NULL,
    actor VARCHAR(20) NOT NULL,
    note VARCHAR(500) NULL,
    occurred_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pipeline_transitions_pipeline FOREIGN KEY (pipeline_id) REFERENCES career_pipelines (id) ON DELETE CASCADE,
    CONSTRAINT fk_pipeline_transitions_from_stage FOREIGN KEY (from_stage_id) REFERENCES pipeline_stages (id),
    CONSTRAINT fk_pipeline_transitions_to_stage FOREIGN KEY (to_stage_id) REFERENCES pipeline_stages (id),
    CONSTRAINT chk_pipeline_transitions_actor CHECK (actor IN ('USER', 'SYSTEM', 'MIGRATION'))
);
CREATE INDEX idx_pipeline_transitions_history ON pipeline_stage_transitions(pipeline_id, occurred_at, id);
