-- Knowledge import & extraction (H2)
-- NOTE: schema must stay equivalent to MySQL V27__knowledge_import_extraction.sql

CREATE TABLE knowledge_extracted_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_extracted_document UNIQUE (document_id),
    CONSTRAINT fk_knowledge_extracted_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_extracted_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    source_file_id BIGINT NOT NULL,
    job_status VARCHAR(16) NOT NULL,
    error_code VARCHAR(32) NULL,
    started_at TIMESTAMP(3) NULL,
    finished_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_import_job_document UNIQUE (document_id),
    CONSTRAINT fk_knowledge_import_job_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_import_job_source FOREIGN KEY (source_file_id)
        REFERENCES knowledge_source_files (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_import_job_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_knowledge_import_jobs_user_status ON knowledge_import_jobs(user_id, job_status);
