-- Knowledge classification & keyword search (H2)
-- NOTE: schema must stay equivalent to MySQL V28__knowledge_classification_search.sql

CREATE TABLE knowledge_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(40) NOT NULL,
    normalized_name VARCHAR(40) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_category_user_name UNIQUE (user_id, normalized_name),
    CONSTRAINT fk_knowledge_category_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(40) NOT NULL,
    normalized_name VARCHAR(40) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_tag_user_name UNIQUE (user_id, normalized_name),
    CONSTRAINT fk_knowledge_tag_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_document_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_doc_category_document UNIQUE (document_id),
    CONSTRAINT uk_knowledge_doc_category_pair UNIQUE (document_id, category_id),
    CONSTRAINT fk_knowledge_doc_category_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_category_category FOREIGN KEY (category_id)
        REFERENCES knowledge_categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_category_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_document_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_doc_tag_pair UNIQUE (document_id, tag_id),
    CONSTRAINT fk_knowledge_doc_tag_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_tag_tag FOREIGN KEY (tag_id)
        REFERENCES knowledge_tags (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_tag_user FOREIGN KEY (user_id) REFERENCES users (id)
);
