DROP TABLE IF EXISTS pipeline_stage_transitions;
DROP TABLE IF EXISTS pipeline_stages;
DROP TABLE IF EXISTS career_pipelines;
DROP TABLE IF EXISTS resume_versions;
DROP TABLE IF EXISTS resumes;
DROP TABLE IF EXISTS job_descriptions;
DROP TABLE IF EXISTS users;

CREATE TABLE users (id BIGINT PRIMARY KEY, display_name VARCHAR(80) NOT NULL);
CREATE TABLE job_descriptions (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL);
CREATE TABLE resumes (id BIGINT PRIMARY KEY, user_id BIGINT NOT NULL, deleted_at TIMESTAMP NULL);
CREATE TABLE resume_versions (id BIGINT PRIMARY KEY, resume_id BIGINT NOT NULL);

CREATE TABLE career_pipelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_project_id BIGINT NULL,
    name VARCHAR(120) NOT NULL,
    company_name VARCHAR(120) NOT NULL,
    role_title VARCHAR(160) NOT NULL,
    job_description_id BIGINT NULL,
    resume_version_id BIGINT NULL,
    lifecycle VARCHAR(20) NOT NULL,
    outcome VARCHAR(20) NULL,
    current_stage_id BIGINT NULL,
    archived_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pipeline_stages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL,
    name VARCHAR(80) NOT NULL,
    position_index INT NOT NULL,
    state VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_pipeline_stages_position UNIQUE (pipeline_id, position_index)
);

CREATE TABLE pipeline_stage_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_id BIGINT NOT NULL,
    from_stage_id BIGINT NULL,
    to_stage_id BIGINT NOT NULL,
    actor VARCHAR(20) NOT NULL,
    note VARCHAR(500) NULL,
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (id, display_name) VALUES (1, 'Local User'), (2, 'Other User');
INSERT INTO job_descriptions (id, user_id) VALUES (10, 1), (20, 2);
INSERT INTO resumes (id, user_id, deleted_at) VALUES (30, 1, NULL), (40, 2, NULL);
INSERT INTO resume_versions (id, resume_id) VALUES (31, 30), (41, 40);
