DROP TABLE IF EXISTS interview_question_set_items;
DROP TABLE IF EXISTS interview_question_sets;
DROP TABLE IF EXISTS interview_plans;
DROP TABLE IF EXISTS resume_versions;
DROP TABLE IF EXISTS resumes;
DROP TABLE IF EXISTS job_descriptions;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL
);

CREATE TABLE resumes (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    kind VARCHAR(24) NOT NULL DEFAULT 'GENERAL',
    current_version_id BIGINT NULL,
    archived_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE resume_versions (
    id BIGINT PRIMARY KEY,
    resume_id BIGINT NOT NULL,
    parent_version_id BIGINT NULL,
    version_no INT NOT NULL,
    content_json CLOB NOT NULL,
    change_summary VARCHAR(500) NULL,
    created_by_type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job_descriptions (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_title VARCHAR(200) NOT NULL
);

CREATE TABLE interview_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    mode VARCHAR(32) NOT NULL DEFAULT 'ROLE_BASED',
    context_contract_version VARCHAR(16) NOT NULL DEFAULT '1',
    start_context_snapshot_json CLOB NULL,
    resume_version_id BIGINT NOT NULL,
    job_description_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL DEFAULT '多轮模拟面试',
    question_count INT NOT NULL DEFAULT 5,
    persona_plan_json CLOB NOT NULL,
    focus_tags_json CLOB NULL,
    supplement_text CLOB NULL,
    summary_json CLOB NULL,
    summary_generated_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_interview_plans_mode CHECK (mode IN ('ROLE_BASED', 'KNOWLEDGE_TRAINING', 'EXPERIENCE_SIMULATION'))
);

CREATE TABLE interview_question_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_note VARCHAR(500) NULL,
    archived_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_interview_question_sets_source
        CHECK (source_type IN ('USER_MANUAL', 'IMPORTED_EXPERIENCE', 'GENERATED_PRACTICE'))
);

CREATE TABLE interview_question_set_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL,
    position_index INT NOT NULL,
    question_text VARCHAR(1000) NOT NULL,
    CONSTRAINT uk_interview_question_set_items UNIQUE (set_id, position_index)
);

INSERT INTO users VALUES (1, '测试用户'), (2, '其他用户');
INSERT INTO resumes (id, user_id, title) VALUES (1, 1, '测试简历');
INSERT INTO resume_versions (id, resume_id, version_no, content_json, created_by_type) VALUES (10, 1, 1, '{}', 'user');
INSERT INTO job_descriptions (id, user_id, job_title) VALUES (100, 1, 'Java 后端');
INSERT INTO interview_plans (user_id, resume_version_id, job_description_id, persona_plan_json) VALUES (1, 10, 100, '[]');

-- 模拟 V20 迁移的回填（在数据插入后执行）：旧计划按现有外键生成兼容快照
UPDATE interview_plans
SET start_context_snapshot_json = CONCAT(
    '{"mode":"ROLE_BASED","contextContractVersion":"1","resumeVersionId":', resume_version_id,
    ',"jobDescriptionId":', job_description_id, '}')
WHERE start_context_snapshot_json IS NULL;
