DROP TABLE IF EXISTS job_projects;
DROP TABLE IF EXISTS resume_versions;
DROP TABLE IF EXISTS resumes;
DROP TABLE IF EXISTS job_descriptions;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL
);

CREATE TABLE job_descriptions (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_title VARCHAR(200) NOT NULL
);

CREATE TABLE resumes (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    deleted_at TIMESTAMP NULL
);

CREATE TABLE resume_versions (
    id BIGINT PRIMARY KEY,
    resume_id BIGINT NOT NULL,
    version_no INT NOT NULL
);

CREATE TABLE job_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    job_description_id BIGINT NULL,
    resume_version_id BIGINT NULL,
    archived_at TIMESTAMP NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users VALUES (1, '本地用户'), (2, '其他用户');
INSERT INTO job_descriptions VALUES (10, 1, 'Java 工程师'), (20, 2, '其他岗位');
INSERT INTO resumes VALUES (30, 1, '我的简历', NULL), (40, 2, '其他简历', NULL);
INSERT INTO resume_versions VALUES (31, 30, 1), (41, 40, 1);
INSERT INTO job_projects (
    id, user_id, name, status, job_description_id, resume_version_id,
    archived_at, deleted_at, created_at, updated_at
) VALUES
    (100, 1, '进行中的项目', 'active', 10, 31, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (101, 1, '已归档项目', 'archived', NULL, NULL, CURRENT_TIMESTAMP, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (102, 1, '已删除项目', 'active', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (200, 2, '其他用户项目', 'active', 20, 41, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE job_projects ALTER COLUMN id RESTART WITH 300;
