DROP TABLE IF EXISTS knowledge_cleanup_jobs;
DROP TABLE IF EXISTS knowledge_delete_confirmations;
DROP TABLE IF EXISTS knowledge_document_tags;
DROP TABLE IF EXISTS knowledge_document_categories;
DROP TABLE IF EXISTS knowledge_tags;
DROP TABLE IF EXISTS knowledge_categories;
DROP TABLE IF EXISTS knowledge_import_jobs;
DROP TABLE IF EXISTS knowledge_extracted_contents;
DROP TABLE IF EXISTS knowledge_source_files;
DROP TABLE IF EXISTS knowledge_documents;
DROP TABLE IF EXISTS users;

CREATE TABLE users (id BIGINT PRIMARY KEY, display_name VARCHAR(80) NOT NULL);
INSERT INTO users (id, display_name) VALUES (1, '本地用户'), (2, '另一用户');

CREATE TABLE knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    source_type VARCHAR(16) NOT NULL,
    processing_status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_documents_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_knowledge_documents_user_updated ON knowledge_documents(user_id, updated_at, id);

CREATE TABLE knowledge_source_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_relative_path VARCHAR(512) NOT NULL,
    mime_type VARCHAR(128) NULL,
    extension VARCHAR(64) NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    sha256 VARCHAR(64) NOT NULL,
    availability VARCHAR(16) NOT NULL,
    staging_relative_path VARCHAR(512) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_source_file_document UNIQUE (document_id),
    CONSTRAINT uk_knowledge_source_file_sha UNIQUE (user_id, sha256),
    CONSTRAINT fk_knowledge_source_file_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_source_file_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_extracted_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_extracted_document UNIQUE (document_id),
    CONSTRAINT fk_knowledge_extracted_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_extracted_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    source_file_id BIGINT NOT NULL,
    job_status VARCHAR(16) NOT NULL,
    error_code VARCHAR(32) NULL,
    started_at TIMESTAMP(3) NULL,
    finished_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_import_job_document UNIQUE (document_id),
    CONSTRAINT fk_knowledge_import_job_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_import_job_source FOREIGN KEY (source_file_id)
        REFERENCES knowledge_source_files (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_import_job_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_knowledge_import_jobs_user_status ON knowledge_import_jobs(user_id, job_status);
CREATE TABLE knowledge_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(40) NOT NULL,
    normalized_name VARCHAR(40) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_category_user_name UNIQUE (user_id, normalized_name),
    CONSTRAINT fk_knowledge_category_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(40) NOT NULL,
    normalized_name VARCHAR(40) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_tag_user_name UNIQUE (user_id, normalized_name),
    CONSTRAINT fk_knowledge_tag_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_document_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_doc_category_document UNIQUE (document_id),
    CONSTRAINT uk_knowledge_doc_category_pair UNIQUE (document_id, category_id),
    CONSTRAINT fk_knowledge_doc_category_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_category_category FOREIGN KEY (category_id)
        REFERENCES knowledge_categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_category_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE knowledge_document_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_doc_tag_pair UNIQUE (document_id, tag_id),
    CONSTRAINT fk_knowledge_doc_tag_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_tag_tag FOREIGN KEY (tag_id)
        REFERENCES knowledge_tags (id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_doc_tag_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE TABLE knowledge_delete_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP(3) NOT NULL,
    consumed_at TIMESTAMP(3) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_delete_confirm_document UNIQUE (document_id),
    CONSTRAINT fk_knowledge_delete_confirm_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_knowledge_delete_confirm_document FOREIGN KEY (document_id)
        REFERENCES knowledge_documents (id) ON DELETE CASCADE
);

CREATE TABLE knowledge_cleanup_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    source_relative_path VARCHAR(512) NULL,
    job_status VARCHAR(16) NOT NULL,
    error_code VARCHAR(32) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP(3) NULL,
    finished_at TIMESTAMP(3) NULL,
    CONSTRAINT fk_knowledge_cleanup_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_knowledge_cleanup_user_status ON knowledge_cleanup_jobs(user_id, job_status);
