DROP TABLE IF EXISTS schedule_events;
DROP TABLE IF EXISTS job_descriptions;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    display_name VARCHAR(120) NOT NULL
);

CREATE TABLE job_descriptions (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    job_title VARCHAR(200) NOT NULL
);

CREATE TABLE schedule_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NULL,
    notes VARCHAR(1000) NULL,
    job_description_id BIGINT NULL,
    deleted_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users VALUES (1, '本地用户'), (2, '其他用户');
INSERT INTO job_descriptions VALUES (10, 1, 'Java 工程师'), (20, 2, '其他岗位');
INSERT INTO schedule_events (
    id, user_id, title, event_type, start_time, end_time, notes,
    job_description_id, deleted_at, created_at, updated_at
) VALUES
    (100, 1, '腾讯技术面', 'interview', TIMESTAMP '2026-08-25 14:00:00', TIMESTAMP '2026-08-25 15:00:00', '第一轮', 10, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (101, 1, '在线笔试', 'exam', TIMESTAMP '2026-08-28 19:00:00', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (102, 1, '已删除的跟进', 'followup', TIMESTAMP '2026-08-30 10:00:00', NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (200, 2, '其他用户日程', 'other', TIMESTAMP '2026-08-26 09:00:00', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

ALTER TABLE schedule_events ALTER COLUMN id RESTART WITH 300;
